### ISSUE TITLE
bugs in parsing feeds

### ISSUE THREAD

**Issue by abbra** [freeipa/freeipa-planet#10]
Now that we recovered build process, I can see that some updates cause issues with the current code. The following example comes from https://github.com/freeipa/freeipa-planet/actions/runs/10547421891/job/29220082170:
```
DEBUG:planet:Last Modified: 2024-08-25T13:37:26+00:00
ERROR:planet.runner:Update of <https://floblanc.wordpress.com/tag/freeipa/feed/> failed
Traceback (most recent call last):
  File "/opt/app-root/src/planet/planet/__init__.py", line 245, in run
    channel.update()
  File "/opt/app-root/src/planet/planet/__init__.py", line 653, in update
    self.update_entries(info.entries)
  File "/opt/app-root/src/planet/planet/__init__.py", line 759, in update_entries
    item.update(entry)
  File "/opt/app-root/src/planet/planet/__init__.py", line 882, in update
    if item.type == 'text/html':
  File "/opt/app-root/src/planet/planet/feedparser.py", line 237, in __getattr__
    raise AttributeError, "object has no attribute '%s'" % key
AttributeError: object has no attribute 'type'
```

**Comment by abbra** [comment]
This affects all wordpress-based feeds, it seems. As a result, none of their entries are visible.
